### ISSUE TITLE
Impressive! Some suggestion how to improve

### ISSUE THREAD

**Issue by AlexandrGraschenkov** [aslanyanhaik/RoundCode#11]
I never thought that something that possible to do in `Swift`. Well done! 👍 

Here some ideas to improve performance of your algo:

1) The slowest part of your algo it control point detector. If you will use simplest structure here, you will have better performance and it will be possible to process full image.

``` Swift
  static let lightBackgroundRange = UInt8(0)...UInt8(180) // simple compare better: pixel < 180 
  static let darkBackgroundRange = UInt8(100)...UInt8(255) // simple compare better: pixel > 100 
```
> I recommend to perform threshold separately. `Accelerate` framework can help

<br>

``` Swift
let bit = pixelThreshold.contains(data[x, y]) ? RCBit.one : RCBit.zero
```
> You probably don't need `RCBit` abstraction. `typealias` around `bool` will works better and pretty informative

<br>

``` Swift
pixelPatterns[pixelPatterns.count - 1] = lastPattern
```
> This operation call lot of times. Just with change `struct` to `class` and you can remove this line

<br>
2) Reed Solomon codes. Additional you will get error restoration. You have interesting idea with something like `hash` with `RCMatrix` (if I understand it right). To make orientation working, you can try 4 possible orientation on decode bits. It's stupid and simple solution.

---

You awesome! =)

**Comment by aslanyanhaik** [comment]
@AlexandrGraschenkov thank you very much for your feedback and suggestions 👍🏻
1. I do need to use Accelerate. I realized that during development. 
2. Regarding `pixelPatterns[pixelPatterns.count - 1] = lastPattern` Turns out using structs were much faster, since classes are stored in the heap.  
3. I was planning to integrate "Reed Solomon", but didn't have enough time to finish. So I ended up with "hash" verification. The parity and matrix multiplication logic is there, so in future versions will add error code.

The goal for this project was to implement everything in Swift without OpenCV. It was harder than I thought. Hopefully, the performance will improve after integrating Accelerate.

**Comment by aslanyanhaik** [comment]
I just noticed you have a much much better version of QR scanner. Do you have twitter? I would like to connect with you.

**Comment by AlexandrGraschenkov** [comment]
I don't have twitter =)

2) If so, then better to perform changes directly in array. In Instruments you can see that this line take pretty much time for execution. You copy every time whole structure data. Or you can perform update only when row of zeros/ones switches to ones/zeros.

You can see implementation of dot detector inside my repo. In `Swift` implementation this code may be more compact and faster current approach.

**Comment by mrousavy** [comment]
@aslanyanhaik have you worked out the performance issue @AlexandrGraschenkov mentioned?
